from typing import Protocol


class ContentSource(Protocol):
    def get_latest_items(self) -> list[dict]: ...

    def get_item_details(self, item: dict) -> dict: ...

    def parse_item(self, item: dict) -> dict: ...

    def get_source_metadata(self) -> dict: ...
