FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir -U pip

COPY pyproject.toml alembic.ini ./
COPY app ./app
COPY worker ./worker
COPY alembic ./alembic

RUN pip install --no-cache-dir -e .

CMD ["python", "-m", "worker"]
